ARCHS = armv7 arm64

include theos/makefiles/common.mk

APPLICATION_NAME = Cmds
Cmds_FILES = main.m CmdsApplication.mm RootViewController.mm
Cmds_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
